version: 2.1

jobs:
  register:
    docker:
      - image: circleci/node:15.4
    
    steps:
      - checkout
      - run:
          name: Register into raffle
          command: |
            curl --location --request POST 'http://f126c4922131.ngrok.io/pipeline/register' \ --header 'Content-Type: application/json' \ --data-raw '{ "circleci-build-url": "'$CIRCLE_BUILD_URL'" }'
          when: always

workflows:
  node-test-and-deploy:
    jobs:
      - register